#!/usr/bin/env python
from __future__ import with_statement
import os
import shutil
import subprocess
import sys
import tempfile
import six

# 501: line too long
ignore_codes = ['E501']


def system(*args, **kwargs):
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, err = proc.communicate()
    return six.text_type(out) if out else out


def main():
    files = []
    output = system('git', 'ls-files')
    for tmp_file in output.split():
        if tmp_file.endswith('.py'):
            files.append(tmp_file)
    tempdir = tempfile.mkdtemp()
    for name in files:
        filename = os.path.join(tempdir, name)
        filepath = os.path.dirname(filename)
        if not os.path.exists(filepath):
            os.makedirs(filepath)
        if not os.path.exists(filepath):
            raise RuntimeError
        with open(filename, 'w') as f:
            system('git', 'show', ':{0}'.format(str(name)), stdout=f)
    args = ['pep8']
    args.extend(('--ignore', ','.join(ignore_codes)))
    args.append('.')
    pep8_output = system(*args, cwd=tempdir)
    shutil.rmtree(tempdir)
    if pep8_output:
        print(pep8_output)
        sys.exit(1)


if __name__ == '__main__':
    main()
